CREATE TABLE DBM_XDN_LOG (
    MSTR_ID VARCHAR2(100) NULL,
    --TRY_ID VARCHAR2(10) NULL,
    RUN_ID NUMBER NULL,
    SRC_OWNER VARCHAR2(30) NULL,
    SRC_TABLE_NAME VARCHAR2(128) NULL,
    TGT_OWNER VARCHAR2(30) NULL,
    TGT_TABLE_NAME VARCHAR2(128) NULL,
    MIG_TYPE VARCHAR2(10) NULL,
    STATUS VARCHAR2(10) NULL,
    ROW_CNT_SRC NUMBER NULL,
    ROW_CNT_TGT NUMBER NULL,
    START_TIME DATE NULL,
    END_TIME DATE NULL,
    ERROR_MSG VARCHAR2(4000) NULL
)