CREATE TABLE DBADM.DBM_MIG_COL_MAP
(
    TGT_OWNER VARCHAR2(30) NOT NULL,
    TGT_TABLE_NAME VARCHAR2(128) NOT NULL,
    SRC_OWNER VARCHAR2(30) NOT NULL,
    SRC_TABLE_NAME VARCHAR2(128) NOT NULL,
    TGT_COL VARCHAR2(128) NOT NULL,
    SRC_COL VARCHAR2(128) NULL,
    MAP_FLAG VARCHAR2(10) NOT NULL,
    DEFAULT_VAL VARCHAR2(1000) NULL,
    REMARK VARCHAR2(500) NULL,
    CONSTRAINT PK_DBM_MIG_COL_MAP PRIMARY KEY (TGT_OWNER, TGT_TABLE_NAME, SRC_OWNER, SRC_TABLE_NAME, TGT_COL)
)
