CREATE TABLE DBADM.DBM_MIG_COL_MAP
(
    SRC_OWNER VARCHAR2(30) NOT NULL,
    SRC_TABLE_NAME VARCHAR2(128) NOT NULL,
    TGT_OWNER VARCHAR2(30) NOT NULL,
    TGT_TABLE_NAME VARCHAR2(128) NOT NULL,
    TGT_COL VARCHAR2(128) NOT NULL,
    SRC_COL VARCHAR2(128) NULL,
    MAP_FLAG VARCHAR2(10) NOT NULL,
    DEFAULT_VAL VARCHAR2(1000) NULL,
    REMARK VARCHAR2(500) NULL,
    CONSTRAINT PK_DBM_MIG_COL_MAP PRIMARY KEY (SRC_OWNER, SRC_TABLE_NAME, TGT_OWNER, TGT_TABLE_NAME, TGT_COL)
)

-- existing table (created with TGT_OWNER / TGT_TABLE_NAME first) : column order can not be changed by ALTER, recreate it
-- ALTER TABLE DBADM.DBM_MIG_COL_MAP RENAME TO DBM_MIG_COL_MAP_OLD;
-- ALTER TABLE DBADM.DBM_MIG_COL_MAP_OLD DROP CONSTRAINT PK_DBM_MIG_COL_MAP;   -- PK name is reused by the new table
-- CREATE TABLE DBADM.DBM_MIG_COL_MAP ( ... above ... );
-- INSERT INTO DBADM.DBM_MIG_COL_MAP (SRC_OWNER, SRC_TABLE_NAME, TGT_OWNER, TGT_TABLE_NAME, TGT_COL, SRC_COL, MAP_FLAG, DEFAULT_VAL, REMARK)
-- SELECT SRC_OWNER, SRC_TABLE_NAME, TGT_OWNER, TGT_TABLE_NAME, TGT_COL, SRC_COL, MAP_FLAG, DEFAULT_VAL, REMARK FROM DBADM.DBM_MIG_COL_MAP_OLD;
-- COMMIT;
-- DROP TABLE DBADM.DBM_MIG_COL_MAP_OLD;
