CREATE TABLE DBADM.DBM_MIG_COL_MAP
(
    MSTR_ID VARCHAR2(100) NOT NULL,
    COL_SEQ NUMBER NOT NULL,
    TGT_COL VARCHAR2(128) NOT NULL,
    SRC_COL VARCHAR2(128) NULL,
    DEFAULT_VAL VARCHAR2(1000) NULL,
    REMARK VARCHAR2(500) NULL,
    CONSTRAINT PK_DBM_MIG_COL_MAP PRIMARY KEY (MSTR_ID, TGT_COL)
)
