-- 3. ASIS_OBJECT COUNT CREATE
DROP TABLE DBADM.MIG_OBJ_CNT_ASIS PURGE;

CREATE TABLE DBADM.MIG_OBJ_CNT_ASIS
(
DB VARCHAR(10) NOT NULL,
OBJECT_NAME VARCHAR(100) NOT NULL,
OWNER VARCHAR(20) NOT NULL,
OBJECT_TYPE VARCHAR(100) NOT NULL,
CNT NUMBER NOT NULL
);

-- 2. CONSTRAINT
INSERT INTO DBADM.MIG_OBJ_CNT_ASIS
SELECT 'ASIS'                     AS DB
,'CONSTRAINT'                     AS OBJECT_NAME
,A.OWNER                          AS OWNER
,'CONSTRAINT_'||A.CONSTRAINT_TYPE AS OBJECT_TYPE
,COUNT(1)                         AS CNT
FROM DBA_ASIS_CONSTRAINTS A,DBADM.MIG_TAB_LIST B
WHERE 1=1
AND A.OWNER = B.OWNER
AND A.TABLE_NAME = B.TABLE_NAME
GROUP BY A.OWNER,A.CONSTRAINT_TYPE;
COMMIT;

-- 3. TABLE
INSERT INTO DBADM.MIG_OBJ_CNT_ASIS
SELECT 'ASIS'                     AS DB
,'TABLE'                          AS OBJECT_NAME
,A.OWNER                          AS OWNER
,'TABLE'                          AS OBJECT_TYPE
,COUNT(1)                         AS CNT
FROM DBA_ASIS_TABLES A,DBADM.MIG_TAB_LIST B
WHERE 1=1
AND A.OWNER = B.OWNER
AND A.TABLE_NAME = B.TABLE_NAME
GROUP BY A.OWNER;
COMMIT;

-- 4. TABLE PARTITION
INSERT INTO DBADM.MIG_OBJ_CNT_ASIS
SELECT 'ASIS'                     AS DB
,'TABLE PARITTION'                AS OBJECT_NAME
,A.table_OWNER                    AS OWNER
,'TABLE PARITTION'                AS OBJECT_TYPE
,COUNT(1)                         AS CNT
FROM DBA_ASIS_TAB_PARTITIONS A,DBADM.MIG_TAB_LIST B
WHERE 1=1
AND A.table_OWNER = B.OWNER
AND A.TABLE_NAME = B.TABLE_NAME
GROUP BY A.table_OWNER;
COMMIT;

-- 6. INDEX
INSERT INTO DBADM.MIG_OBJ_CNT_ASIS
SELECT 'ASIS'                     AS DB
,'INDEX'                          AS OBJECT_NAME
,A.OWNER                          AS OWNER
,'INDEX'                          AS OBJECT_TYPE
,COUNT(1)                         AS CNT
FROM DBA_ASIS_INDEXES A,DBADM.MIG_TAB_LIST B
WHERE 1=1
AND A.OWNER = B.OWNER
AND A.TABLE_NAME = B.TABLE_NAME
GROUP BY A.OWNER;
COMMIT;

-- 7. PARTITION INDEX
INSERT INTO DBADM.MIG_OBJ_CNT_ASIS
SELECT 'ASIS'                     AS DB
,'INDEX PARITTION'                AS OBJECT_NAME
,A.INDEX_OWNER                    AS OWNER
,'INDEX PARITTION'                AS OBJECT_TYPE
,COUNT(1)                         AS CNT
FROM DBA_ASIS_IND_PARTITIONS A,
     DBADM.MIG_TAB_LIST B,
     DBA_ASIS_INDEXES C
WHERE 1=1
AND A.INDEX_OWNER = C.OWNER
AND A.INDEX_NAME = C.INDEX_NAME
AND B.TABLE_NAME = C.TABLE_NAME
GROUP BY A.INDEX_OWNER;

COMMIT;

--8. OTHERS OBJECTS
INSERT INTO DBADM.MIG_OBJ_CNT_ASIS
SELECT 'ASIS'                     AS DB
,'OTHERS OBJECT'                  AS OBJECT_NAME
,A.OWNER                          AS OWNER
--, A.OBJECT_NAME
,A.OBJECT_TYPE                    AS OBJECT_TYPE
,COUNT(1)                         AS CNT
FROM DBA_ASIS_OTHER_OBJECTS A,DBA_OBJECTS B
WHERE A.OWNER = B.OWNER
AND A.OBJECT_NAME = B.OBJECT_NAME
AND A.OBJECT_TYPE = B.OBJECT_TYPE
GROUP BY A.OWNER, A.OBJECT_TYPE;
COMMIT;

