-- 5. ASIS <-> TOBE OBJECT GAP CHECK
--    Compare object counts between DBADM.MIG_OBJ_CNT_ASIS and DBADM.MIG_OBJ_CNT_TOBE.
--    ASIS and TOBE schema (OWNER) names can differ (e.g. EBDBA -> GEBOWN), so the gap
--    is rolled up by OBJECT_NAME + OBJECT_TYPE (CNT summed across owners).
--    GAP = ASIS_CNT - TOBE_CNT  ( 0 = OK, <>0 = mismatch, one side NULL = missing ).

SET LINES 200 PAGES 200 FEED OFF
COL OBJECT_NAME FOR A20
COL OBJECT_TYPE FOR A25
COL ASIS_CNT    FOR 9,999,990
COL TOBE_CNT    FOR 9,999,990
COL GAP         FOR 9,999,990

PROMPT
PROMPT ===================== OBJECT COUNT GAP (ASIS - TOBE) =====================

SELECT NVL(A.OBJECT_NAME, T.OBJECT_NAME) AS OBJECT_NAME
     , NVL(A.OBJECT_TYPE, T.OBJECT_TYPE) AS OBJECT_TYPE
     , NVL(A.CNT, 0)                     AS ASIS_CNT
     , NVL(T.CNT, 0)                     AS TOBE_CNT
     , NVL(A.CNT, 0) - NVL(T.CNT, 0)     AS GAP
FROM   ( SELECT OBJECT_NAME, OBJECT_TYPE, SUM(CNT) AS CNT
           FROM DBADM.MIG_OBJ_CNT_ASIS
          GROUP BY OBJECT_NAME, OBJECT_TYPE ) A
FULL OUTER JOIN
       ( SELECT OBJECT_NAME, OBJECT_TYPE, SUM(CNT) AS CNT
           FROM DBADM.MIG_OBJ_CNT_TOBE
          GROUP BY OBJECT_NAME, OBJECT_TYPE ) T
  ON  A.OBJECT_NAME = T.OBJECT_NAME
  AND A.OBJECT_TYPE = T.OBJECT_TYPE
ORDER BY OBJECT_NAME, OBJECT_TYPE;

PROMPT
PROMPT ===================== MISMATCH ONLY (GAP <> 0) ==========================

SELECT OBJECT_NAME, OBJECT_TYPE, ASIS_CNT, TOBE_CNT, GAP
FROM (
    SELECT NVL(A.OBJECT_NAME, T.OBJECT_NAME) AS OBJECT_NAME
         , NVL(A.OBJECT_TYPE, T.OBJECT_TYPE) AS OBJECT_TYPE
         , NVL(A.CNT, 0)                     AS ASIS_CNT
         , NVL(T.CNT, 0)                     AS TOBE_CNT
         , NVL(A.CNT, 0) - NVL(T.CNT, 0)     AS GAP
    FROM   ( SELECT OBJECT_NAME, OBJECT_TYPE, SUM(CNT) AS CNT
               FROM DBADM.MIG_OBJ_CNT_ASIS
              GROUP BY OBJECT_NAME, OBJECT_TYPE ) A
    FULL OUTER JOIN
           ( SELECT OBJECT_NAME, OBJECT_TYPE, SUM(CNT) AS CNT
               FROM DBADM.MIG_OBJ_CNT_TOBE
              GROUP BY OBJECT_NAME, OBJECT_TYPE ) T
      ON  A.OBJECT_NAME = T.OBJECT_NAME
      AND A.OBJECT_TYPE = T.OBJECT_TYPE
)
WHERE ASIS_CNT - TOBE_CNT <> 0
ORDER BY OBJECT_NAME, OBJECT_TYPE;

PROMPT
PROMPT ===================== RESULT ============================================
SELECT CASE WHEN COUNT(*) = 0 THEN 'PASS : ASIS = TOBE (no gap)'
            ELSE 'CHECK: ' || COUNT(*) || ' object type(s) mismatched'
       END AS GAP_RESULT
FROM (
    SELECT NVL(A.OBJECT_NAME, T.OBJECT_NAME) AS OBJECT_NAME
         , NVL(A.OBJECT_TYPE, T.OBJECT_TYPE) AS OBJECT_TYPE
         , NVL(A.CNT, 0) - NVL(T.CNT, 0)     AS GAP
    FROM   ( SELECT OBJECT_NAME, OBJECT_TYPE, SUM(CNT) AS CNT
               FROM DBADM.MIG_OBJ_CNT_ASIS
              GROUP BY OBJECT_NAME, OBJECT_TYPE ) A
    FULL OUTER JOIN
           ( SELECT OBJECT_NAME, OBJECT_TYPE, SUM(CNT) AS CNT
               FROM DBADM.MIG_OBJ_CNT_TOBE
              GROUP BY OBJECT_NAME, OBJECT_TYPE ) T
      ON  A.OBJECT_NAME = T.OBJECT_NAME
      AND A.OBJECT_TYPE = T.OBJECT_TYPE
)
WHERE GAP <> 0;
